name: ml-intermediate

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pygraphviz

  - pip:
    - ploomber
    - soopervisor
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation
    - ipywidgets
