name: mlflow

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pygraphviz

  - pip:
    - ploomber
    - pandas
    - scikit-learn
    - sklearn-evaluation
    - jupyter
    - mlflow
