name: spec-api-directory

dependencies:
  - python=3.10
  - pip
  - pip:
    - ploomber
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - seaborn
    - pyarrow
    - sklearn-evaluation
